/*左侧导航栏菜单生成的内容*/
const  menu=[
    {

        title:'内容管理',
        icon:'course_shouye',
        child:[
            {
                path:'/ContentList',
                title:'图文管理',
            },
            {
                path:'/videoContentList',
                title:'视频管理',
            },
            {
                path:'/svipList',
                title:'专题管理',
            },
            {
                path:'/replyList',
                title:'评论管理'
            }
        ]
    },
    {
        title:'活动管理',
        icon:'course_shouye',
        child:[
            {
                path:'/activityList',
                title:'活动管理'
            },
            {
                path:'/addActivity',
                title:'发布活动'
            }
        ]
    },
    {
        title:'标签管理',
        icon:'course_shouye',
        child:[
           {
               path:'/homeTag',
               title:'标签列表'
           }, {
               path:'/tagGroup',
               title:'新建分组'
           }
        ]
    },
    {
        title:'广告管理',
        icon:'course_shouye',
        child:[
			{
			    path:'/advertList',
			    title:'广告列表'
			},{
			    path:'/addAdvert',
			    title:'发布广告'
			},
		],
    },
    {
        title:'用户管理',
        icon:'course_shouye',
        child:[
			{
			    path:'/adminList',
			    title:'管理员管理'
			},{
			    path:'/insiderList',
			    title:'内部人员管理'
			},{
			    path:'/userList',
			    title:'用户管理'
			},
		]
    },
	{ 
	    title:'审核管理',
	    icon:'course_shouye',
	    child:[
	        {
	            path:'/insiderExamineList',
	            title:'内部人员审核'
	        }
	    ]
	},{ 
	    title:'数据统计',
	    icon:'course_shouye',
	    child:[
	        {
	            path:'/interestTagList',
	            title:'用户兴趣标签'
	        },
	        {
	            path:'/enrollList',
	            title:'活动报名'
	        }
	    ]
	},
]

const insiderMenu=[
	{
	
	    title:'内容管理',
	    icon:'course_shouye',
	    child:[
	        {
	            path:'/ContentList',
	            title:'图文管理',
	        },
	        {
	            path:'/videoContentList',
	            title:'视频管理',
	        },
	        {
	            path:'/replyList',
	            title:'评论管理'
	        }
	    ]
	},
	{
	    title:'活动管理',
	    icon:'course_shouye',
	    child:[
	        {
	            path:'/activityList',
	            title:'活动管理'
	        },
	        {
	            path:'/addActivity',
	            title:'发布活动'
	        }
	    ]
	}
]

const userMenu=[
	{
	    title:'内容管理',
	    icon:'course_shouye',
	    child:[
	        {
	            path:'/replyList',
	            title:'评论管理'
	        }
	    ]
	}
]


export default {
    menu,
	insiderMenu,
	userMenu,
}
